# Rota curinga para Single Page Applications (MUITO IMPORTANTE)
# Qualquer URL não encontrada que não for um arquivo public (como as de rotas React Router /dashboard/algo) 
# cairá nesta regra e será roteada para o index.html gerado pelo React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
